# Описание параметров в src/config.hpp

host: "0.0.0.0"
port: 8000
# keep_alive_max_count: 300
# max_request_body_bytes: 2147483647

# storage_path: "/var/lib/fulltext-search-service"

# index_max_word_length: 100

# api_default_limit: 10
# api_max_limit: 1000
# api_max_offset: 10000
# api_max_responses: 5
# rate_limit_requests_per_minute: 120
